# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view\qt_main_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(885, 662)
        MainWindow.setStyleSheet("background-color: rgb(50, 50, 50);\n"
"selection-color: rgb(200, 200, 200);\n"
"")
        self.widget = QtWidgets.QWidget(MainWindow)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.widget)
        self.calendarWidget.setStyleSheet("color: rgb(204, 204, 204);\n"
"alternate-background-color: rgb(255, 159, 146);\n"
"font: 15pt \"MS Serif\";\n"
"selection-background-color: rgb(255, 159, 146);")
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout.addWidget(self.calendarWidget, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.rb_small_garage = QtWidgets.QRadioButton(self.widget)
        self.rb_small_garage.setEnabled(True)
        self.rb_small_garage.setStyleSheet("QRadioButton{\n"
"color: rgb(204, 204, 204);\n"
"font: 15pt \"MS Serif\";\n"
"}\n"
"QRadioButton::indicator {\n"
"    width:                  10px;\n"
"    height:                 10px;\n"
"    border-radius:          7px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:       red;\n"
"    border:                 2px solid rgb(255, 41, 41); \n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(0, 255, 0);\n"
"    border:                 2px solid rgb(41, 255, 41);\n"
"}\n"
"")
        self.rb_small_garage.setCheckable(True)
        self.rb_small_garage.setChecked(False)
        self.rb_small_garage.setAutoExclusive(False)
        self.rb_small_garage.setObjectName("rb_small_garage")
        self.verticalLayout.addWidget(self.rb_small_garage)
        self.rb_celler_door = QtWidgets.QRadioButton(self.widget)
        self.rb_celler_door.setEnabled(False)
        self.rb_celler_door.setStyleSheet("QRadioButton{\n"
"color: rgb(204, 204, 204);\n"
"font: 15pt \"MS Serif\";\n"
"}\n"
"QRadioButton::indicator {\n"
"    width:                  10px;\n"
"    height:                 10px;\n"
"    border-radius:          7px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:       red;\n"
"    border:                 2px solid rgb(255, 41, 41); \n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(0, 255, 0);\n"
"    border:                 2px solid rgb(41, 255, 41);\n"
"}\n"
"")
        self.rb_celler_door.setAutoExclusive(False)
        self.rb_celler_door.setObjectName("rb_celler_door")
        self.verticalLayout.addWidget(self.rb_celler_door)
        self.rb_lights_attic = QtWidgets.QRadioButton(self.widget)
        self.rb_lights_attic.setEnabled(False)
        self.rb_lights_attic.setAutoFillBackground(False)
        self.rb_lights_attic.setStyleSheet("QRadioButton{\n"
"color: rgb(204, 204, 204);\n"
"font: 15pt \"MS Serif\";\n"
"}\n"
"QRadioButton::indicator {\n"
"    width:                  10px;\n"
"    height:                 10px;\n"
"    border-radius:          7px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:       red;\n"
"    border:                 2px solid rgb(255, 41, 41); \n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(0, 255, 0);\n"
"    border:                 2px solid rgb(41, 255, 41);\n"
"}\n"
"")
        self.rb_lights_attic.setAutoExclusive(True)
        self.rb_lights_attic.setObjectName("rb_lights_attic")
        self.verticalLayout.addWidget(self.rb_lights_attic)
        self.rb_attic_door = QtWidgets.QRadioButton(self.widget)
        self.rb_attic_door.setEnabled(False)
        self.rb_attic_door.setStyleSheet("QRadioButton{\n"
"color: rgb(204, 204, 204);\n"
"font: 15pt \"MS Serif\";\n"
"}\n"
"QRadioButton::indicator {\n"
"    width:                  10px;\n"
"    height:                 10px;\n"
"    border-radius:          7px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:       red;\n"
"    border:                 2px solid rgb(255, 41, 41); \n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(0, 255, 0);\n"
"    border:                 2px solid rgb(41, 255, 41);\n"
"}\n"
"")
        self.rb_attic_door.setAutoExclusive(False)
        self.rb_attic_door.setObjectName("rb_attic_door")
        self.verticalLayout.addWidget(self.rb_attic_door)
        self.rb_garden_door_b = QtWidgets.QRadioButton(self.widget)
        self.rb_garden_door_b.setEnabled(False)
        self.rb_garden_door_b.setStyleSheet("QRadioButton{\n"
"color: rgb(204, 204, 204);\n"
"font: 15pt \"MS Serif\";\n"
"}\n"
"QRadioButton::indicator {\n"
"    width:                  10px;\n"
"    height:                 10px;\n"
"    border-radius:          7px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:       red;\n"
"    border:                 2px solid rgb(255, 41, 41); \n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(0, 255, 0);\n"
"    border:                 2px solid rgb(41, 255, 41);\n"
"}\n"
"")
        self.rb_garden_door_b.setAutoExclusive(False)
        self.rb_garden_door_b.setObjectName("rb_garden_door_b")
        self.verticalLayout.addWidget(self.rb_garden_door_b)
        self.rb_motion_detector_2 = QtWidgets.QRadioButton(self.widget)
        self.rb_motion_detector_2.setEnabled(False)
        self.rb_motion_detector_2.setStyleSheet("QRadioButton{\n"
"color: rgb(204, 204, 204);\n"
"font: 15pt \"MS Serif\";\n"
"}\n"
"QRadioButton::indicator {\n"
"    width:                  10px;\n"
"    height:                 10px;\n"
"    border-radius:          7px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:       red;\n"
"    border:                 2px solid rgb(255, 41, 41); \n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(0, 255, 0);\n"
"    border:                 2px solid rgb(41, 255, 41);\n"
"}\n"
"")
        self.rb_motion_detector_2.setAutoExclusive(False)
        self.rb_motion_detector_2.setObjectName("rb_motion_detector_2")
        self.verticalLayout.addWidget(self.rb_motion_detector_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rb_large_garage = QtWidgets.QRadioButton(self.widget)
        self.rb_large_garage.setEnabled(False)
        self.rb_large_garage.setStyleSheet("QRadioButton{\n"
"color: rgb(204, 204, 204);\n"
"font: 15pt \"MS Serif\";\n"
"}\n"
"QRadioButton::indicator {\n"
"    width:                  10px;\n"
"    height:                 10px;\n"
"    border-radius:          7px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:       red;\n"
"    border:                 2px solid rgb(255, 41, 41); \n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(0, 255, 0);\n"
"    border:                 2px solid rgb(41, 255, 41);\n"
"}\n"
"")
        self.rb_large_garage.setAutoExclusive(False)
        self.rb_large_garage.setObjectName("rb_large_garage")
        self.verticalLayout_2.addWidget(self.rb_large_garage)
        self.rb_garden_door = QtWidgets.QRadioButton(self.widget)
        self.rb_garden_door.setEnabled(False)
        self.rb_garden_door.setStyleSheet("QRadioButton{\n"
"color: rgb(204, 204, 204);\n"
"font: 15pt \"MS Serif\";\n"
"}\n"
"QRadioButton::indicator {\n"
"    width:                  10px;\n"
"    height:                 10px;\n"
"    border-radius:          7px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:       red;\n"
"    border:                 2px solid rgb(255, 41, 41); \n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(0, 255, 0);\n"
"    border:                 2px solid rgb(41, 255, 41);\n"
"}\n"
"")
        self.rb_garden_door.setChecked(False)
        self.rb_garden_door.setAutoRepeat(False)
        self.rb_garden_door.setAutoExclusive(False)
        self.rb_garden_door.setObjectName("rb_garden_door")
        self.verticalLayout_2.addWidget(self.rb_garden_door)
        self.rb_light_garage = QtWidgets.QRadioButton(self.widget)
        self.rb_light_garage.setEnabled(False)
        self.rb_light_garage.setStyleSheet("QRadioButton{\n"
"color: rgb(204, 204, 204);\n"
"font: 15pt \"MS Serif\";\n"
"}\n"
"QRadioButton::indicator {\n"
"    width:                  10px;\n"
"    height:                 10px;\n"
"    border-radius:          7px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:       red;\n"
"    border:                 2px solid rgb(255, 41, 41); \n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(0, 255, 0);\n"
"    border:                 2px solid rgb(41, 255, 41);\n"
"}\n"
"")
        self.rb_light_garage.setAutoExclusive(False)
        self.rb_light_garage.setObjectName("rb_light_garage")
        self.verticalLayout_2.addWidget(self.rb_light_garage)
        self.rb_garden_door_a = QtWidgets.QRadioButton(self.widget)
        self.rb_garden_door_a.setEnabled(False)
        self.rb_garden_door_a.setStyleSheet("QRadioButton{\n"
"color: rgb(204, 204, 204);\n"
"font: 15pt \"MS Serif\";\n"
"}\n"
"QRadioButton::indicator {\n"
"    width:                  10px;\n"
"    height:                 10px;\n"
"    border-radius:          7px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:       red;\n"
"    border:                 2px solid rgb(255, 41, 41); \n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(0, 255, 0);\n"
"    border:                 2px solid rgb(41, 255, 41);\n"
"}\n"
"")
        self.rb_garden_door_a.setAutoExclusive(False)
        self.rb_garden_door_a.setObjectName("rb_garden_door_a")
        self.verticalLayout_2.addWidget(self.rb_garden_door_a)
        self.rb_motion_detector_1 = QtWidgets.QRadioButton(self.widget)
        self.rb_motion_detector_1.setEnabled(False)
        self.rb_motion_detector_1.setStyleSheet("QRadioButton{\n"
"color: rgb(204, 204, 204);\n"
"font: 15pt \"MS Serif\";\n"
"}\n"
"QRadioButton::indicator {\n"
"    width:                  10px;\n"
"    height:                 10px;\n"
"    border-radius:          7px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:       red;\n"
"    border:                 2px solid rgb(255, 41, 41); \n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(0, 255, 0);\n"
"    border:                 2px solid rgb(41, 255, 41);\n"
"}\n"
"")
        self.rb_motion_detector_1.setAutoExclusive(False)
        self.rb_motion_detector_1.setObjectName("rb_motion_detector_1")
        self.verticalLayout_2.addWidget(self.rb_motion_detector_1)
        self.rb_motion_detector_3 = QtWidgets.QRadioButton(self.widget)
        self.rb_motion_detector_3.setEnabled(False)
        self.rb_motion_detector_3.setStyleSheet("QRadioButton{\n"
"color: rgb(204, 204, 204);\n"
"font: 15pt \"MS Serif\";\n"
"}\n"
"QRadioButton::indicator {\n"
"    width:                  10px;\n"
"    height:                 10px;\n"
"    border-radius:          7px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:       red;\n"
"    border:                 2px solid rgb(255, 41, 41); \n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(0, 255, 0);\n"
"    border:                 2px solid rgb(41, 255, 41);\n"
"}\n"
"")
        self.rb_motion_detector_3.setAutoExclusive(False)
        self.rb_motion_detector_3.setObjectName("rb_motion_detector_3")
        self.verticalLayout_2.addWidget(self.rb_motion_detector_3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_4.addWidget(self.pushButton_6)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_4.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_4.addWidget(self.pushButton_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_3.addWidget(self.pushButton_3)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_3.addWidget(self.pushButton_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.widget)

        self.retranslateUi(MainWindow)
        self.pushButton_6.clicked.connect(self.rb_small_garage.toggle)
        self.pushButton_4.clicked.connect(self.rb_celler_door.toggle)
        self.pushButton_5.clicked.connect(self.rb_lights_attic.toggle)
        self.pushButton_3.clicked.connect(self.rb_large_garage.toggle)
        self.pushButton.clicked.connect(self.rb_garden_door.toggle)
        self.pushButton_2.clicked.connect(self.rb_light_garage.toggle)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.rb_small_garage.setText(_translate("MainWindow", "kleine Garage"))
        self.rb_celler_door.setText(_translate("MainWindow", "Kellertür"))
        self.rb_lights_attic.setText(_translate("MainWindow", "Licht Dachboden"))
        self.rb_attic_door.setText(_translate("MainWindow", "Dachbodentür"))
        self.rb_garden_door_b.setText(_translate("MainWindow", "Gartentür B"))
        self.rb_motion_detector_2.setText(_translate("MainWindow", "Bewegungsmelder 2"))
        self.rb_large_garage.setText(_translate("MainWindow", "große Garage"))
        self.rb_garden_door.setText(_translate("MainWindow", "Garagentür"))
        self.rb_light_garage.setText(_translate("MainWindow", "Licht Garage"))
        self.rb_garden_door_a.setText(_translate("MainWindow", "Gartentür A"))
        self.rb_motion_detector_1.setText(_translate("MainWindow", "Bewegungsmelder 1"))
        self.rb_motion_detector_3.setText(_translate("MainWindow", "Bewegungsmelder 3"))
        self.pushButton_6.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_4.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_5.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
