# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view\qt_main_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        MainWindow.setStyleSheet("background-color: rgb(50, 50, 50);\n"
"selection-color: rgb(200, 200, 200);\n"
"")
        self.widget = QtWidgets.QWidget(MainWindow)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.rb_small_garage = QtWidgets.QRadioButton(self.widget)
        self.rb_small_garage.setEnabled(True)
        self.rb_small_garage.setStyleSheet("QRadioButton{\n"
"color: rgb(204, 204, 204);\n"
"font: 18pt \"MS Serif\";\n"
"}\n"
"QRadioButton::indicator {\n"
"    width:                  18px;\n"
"    height:                 18px;\n"
"    border-radius:          10px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:       rgb(255, 174, 66);\n"
"    border:                 2px solid rgb(255, 174, 66); \n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(50, 50, 50);\n"
"    border:                 2px solid (50, 50, 50);\n"
"}\n"
"")
        self.rb_small_garage.setCheckable(True)
        self.rb_small_garage.setChecked(True)
        self.rb_small_garage.setAutoExclusive(False)
        self.rb_small_garage.setObjectName("rb_small_garage")
        self.verticalLayout.addWidget(self.rb_small_garage)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.rb_celler_door = QtWidgets.QRadioButton(self.widget)
        self.rb_celler_door.setEnabled(False)
        self.rb_celler_door.setStyleSheet("QRadioButton{\n"
"color: rgb(204, 204, 204);\n"
"font: 18pt \"MS Serif\";\n"
"}\n"
"QRadioButton::indicator {\n"
"    width:                  18px;\n"
"    height:                 18px;\n"
"    border-radius:          10px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:       rgb(255, 174, 66);\n"
"    border:                 2px solid rgb(255, 174, 66); \n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(50, 50, 50);\n"
"    border:                 2px solid (50, 50, 50);\n"
"}\n"
"")
        self.rb_celler_door.setAutoExclusive(False)
        self.rb_celler_door.setObjectName("rb_celler_door")
        self.verticalLayout.addWidget(self.rb_celler_door)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.rb_lights_attic = QtWidgets.QRadioButton(self.widget)
        self.rb_lights_attic.setEnabled(False)
        self.rb_lights_attic.setAutoFillBackground(False)
        self.rb_lights_attic.setStyleSheet("QRadioButton{\n"
"color: rgb(204, 204, 204);\n"
"font: 18pt \"MS Serif\";\n"
"}\n"
"QRadioButton::indicator {\n"
"    width:                  18px;\n"
"    height:                 18px;\n"
"    border-radius:          10px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:       rgb(255, 174, 66);\n"
"    border:                 2px solid rgb(255, 174, 66); \n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(50, 50, 50);\n"
"    border:                 2px solid (50, 50, 50);\n"
"}\n"
"")
        self.rb_lights_attic.setAutoExclusive(True)
        self.rb_lights_attic.setObjectName("rb_lights_attic")
        self.verticalLayout.addWidget(self.rb_lights_attic)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.rb_attic_door = QtWidgets.QRadioButton(self.widget)
        self.rb_attic_door.setEnabled(False)
        self.rb_attic_door.setStyleSheet("QRadioButton{\n"
"color: rgb(204, 204, 204);\n"
"font: 18pt \"MS Serif\";\n"
"}\n"
"QRadioButton::indicator {\n"
"    width:                  18px;\n"
"    height:                 18px;\n"
"    border-radius:          10px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:       rgb(255, 174, 66);\n"
"    border:                 2px solid rgb(255, 174, 66); \n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(50, 50, 50);\n"
"    border:                 2px solid (50, 50, 50);\n"
"}\n"
"\n"
"")
        self.rb_attic_door.setAutoExclusive(False)
        self.rb_attic_door.setObjectName("rb_attic_door")
        self.verticalLayout.addWidget(self.rb_attic_door)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.rb_garden_door_b = QtWidgets.QRadioButton(self.widget)
        self.rb_garden_door_b.setEnabled(False)
        self.rb_garden_door_b.setStyleSheet("QRadioButton{\n"
"color: rgb(204, 204, 204);\n"
"font: 18pt \"MS Serif\";\n"
"}\n"
"QRadioButton::indicator {\n"
"    width:                  18px;\n"
"    height:                 18px;\n"
"    border-radius:          10px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:       rgb(255, 174, 66);\n"
"    border:                 2px solid rgb(255, 174, 66); \n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(50, 50, 50);\n"
"    border:                 2px solid (50, 50, 50);\n"
"}\n"
"")
        self.rb_garden_door_b.setAutoExclusive(False)
        self.rb_garden_door_b.setObjectName("rb_garden_door_b")
        self.verticalLayout.addWidget(self.rb_garden_door_b)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.rb_motion_detector_2 = QtWidgets.QRadioButton(self.widget)
        self.rb_motion_detector_2.setEnabled(False)
        self.rb_motion_detector_2.setStyleSheet("QRadioButton{\n"
"color: rgb(204, 204, 204);\n"
"font: 18pt \"MS Serif\";\n"
"}\n"
"QRadioButton::indicator {\n"
"    width:                  18px;\n"
"    height:                 18px;\n"
"    border-radius:          10px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:       rgb(255, 174, 66);\n"
"    border:                 2px solid rgb(255, 174, 66); \n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(50, 50, 50);\n"
"    border:                 2px solid (50, 50, 50);\n"
"}\n"
"")
        self.rb_motion_detector_2.setAutoExclusive(False)
        self.rb_motion_detector_2.setObjectName("rb_motion_detector_2")
        self.verticalLayout.addWidget(self.rb_motion_detector_2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.rb_large_garage = QtWidgets.QRadioButton(self.widget)
        self.rb_large_garage.setEnabled(False)
        self.rb_large_garage.setStyleSheet("QRadioButton{\n"
"color: rgb(204, 204, 204);\n"
"font: 18pt \"MS Serif\";\n"
"}\n"
"QRadioButton::indicator {\n"
"    width:                  18px;\n"
"    height:                 18px;\n"
"    border-radius:          10px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:       rgb(255, 174, 66);\n"
"    border:                 2px solid rgb(255, 174, 66); \n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(50, 50, 50);\n"
"    border:                 2px solid (50, 50, 50);\n"
"}\n"
"")
        self.rb_large_garage.setAutoExclusive(False)
        self.rb_large_garage.setObjectName("rb_large_garage")
        self.verticalLayout_2.addWidget(self.rb_large_garage)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        self.rb_garden_door = QtWidgets.QRadioButton(self.widget)
        self.rb_garden_door.setEnabled(False)
        self.rb_garden_door.setStyleSheet("QRadioButton{\n"
"color: rgb(204, 204, 204);\n"
"font: 18pt \"MS Serif\";\n"
"}\n"
"QRadioButton::indicator {\n"
"    width:                  18px;\n"
"    height:                 18px;\n"
"    border-radius:          10px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:       rgb(255, 174, 66);\n"
"    border:                 2px solid rgb(255, 174, 66); \n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(50, 50, 50);\n"
"    border:                 2px solid (50, 50, 50);\n"
"}\n"
"")
        self.rb_garden_door.setChecked(False)
        self.rb_garden_door.setAutoRepeat(False)
        self.rb_garden_door.setAutoExclusive(False)
        self.rb_garden_door.setObjectName("rb_garden_door")
        self.verticalLayout_2.addWidget(self.rb_garden_door)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem9)
        self.rb_light_garage = QtWidgets.QRadioButton(self.widget)
        self.rb_light_garage.setEnabled(False)
        self.rb_light_garage.setStyleSheet("QRadioButton{\n"
"color: rgb(204, 204, 204);\n"
"font: 18pt \"MS Serif\";\n"
"}\n"
"QRadioButton::indicator {\n"
"    width:                  18px;\n"
"    height:                 18px;\n"
"    border-radius:          10px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:       rgb(255, 174, 66);\n"
"    border:                 2px solid rgb(255, 174, 66); \n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(50, 50, 50);\n"
"    border:                 2px solid (50, 50, 50);\n"
"}\n"
"")
        self.rb_light_garage.setAutoExclusive(False)
        self.rb_light_garage.setObjectName("rb_light_garage")
        self.verticalLayout_2.addWidget(self.rb_light_garage)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem10)
        self.rb_garden_door_a = QtWidgets.QRadioButton(self.widget)
        self.rb_garden_door_a.setEnabled(False)
        self.rb_garden_door_a.setStyleSheet("QRadioButton{\n"
"color: rgb(204, 204, 204);\n"
"font: 18pt \"MS Serif\";\n"
"}\n"
"QRadioButton::indicator {\n"
"    width:                  18px;\n"
"    height:                 18px;\n"
"    border-radius:          10px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:       rgb(255, 174, 66);\n"
"    border:                 2px solid rgb(255, 174, 66); \n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(50, 50, 50);\n"
"    border:                 2px solid (50, 50, 50);\n"
"}\n"
"")
        self.rb_garden_door_a.setAutoExclusive(False)
        self.rb_garden_door_a.setObjectName("rb_garden_door_a")
        self.verticalLayout_2.addWidget(self.rb_garden_door_a)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem11)
        self.rb_motion_detector_1 = QtWidgets.QRadioButton(self.widget)
        self.rb_motion_detector_1.setEnabled(False)
        self.rb_motion_detector_1.setStyleSheet("QRadioButton{\n"
"color: rgb(204, 204, 204);\n"
"font: 18pt \"MS Serif\";\n"
"}\n"
"QRadioButton::indicator {\n"
"    width:                  18px;\n"
"    height:                 18px;\n"
"    border-radius:          10px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:       rgb(255, 174, 66);\n"
"    border:                 2px solid rgb(255, 174, 66); \n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(50, 50, 50);\n"
"    border:                 2px solid (50, 50, 50);\n"
"}\n"
"")
        self.rb_motion_detector_1.setAutoExclusive(False)
        self.rb_motion_detector_1.setObjectName("rb_motion_detector_1")
        self.verticalLayout_2.addWidget(self.rb_motion_detector_1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem12)
        self.rb_motion_detector_3 = QtWidgets.QRadioButton(self.widget)
        self.rb_motion_detector_3.setEnabled(False)
        self.rb_motion_detector_3.setStyleSheet("QRadioButton{\n"
"color: rgb(204, 204, 204);\n"
"font: 18pt \"MS Serif\";\n"
"}\n"
"QRadioButton::indicator {\n"
"    width:                  18px;\n"
"    height:                 18px;\n"
"    border-radius:          10px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:       rgb(255, 174, 66);\n"
"    border:                 2px solid rgb(255, 174, 66); \n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(50, 50, 50);\n"
"    border:                 2px solid (50, 50, 50);\n"
"}\n"
"")
        self.rb_motion_detector_3.setAutoExclusive(False)
        self.rb_motion_detector_3.setObjectName("rb_motion_detector_3")
        self.verticalLayout_2.addWidget(self.rb_motion_detector_3)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem13)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.widget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.rb_small_garage.setText(_translate("MainWindow", "Kleine Garage"))
        self.rb_celler_door.setText(_translate("MainWindow", "Kellertür"))
        self.rb_lights_attic.setText(_translate("MainWindow", "Licht Dachboden"))
        self.rb_attic_door.setText(_translate("MainWindow", "Dachbodentür"))
        self.rb_garden_door_b.setText(_translate("MainWindow", "Gartentür B"))
        self.rb_motion_detector_2.setText(_translate("MainWindow", "Bewegungsmelder 2"))
        self.rb_large_garage.setText(_translate("MainWindow", "Große Garage"))
        self.rb_garden_door.setText(_translate("MainWindow", "Garagentür"))
        self.rb_light_garage.setText(_translate("MainWindow", "Licht Garage"))
        self.rb_garden_door_a.setText(_translate("MainWindow", "Gartentür A"))
        self.rb_motion_detector_1.setText(_translate("MainWindow", "Bewegungsmelder 1"))
        self.rb_motion_detector_3.setText(_translate("MainWindow", "Bewegungsmelder 3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
